apiVersion: v1
kind: Pod
metadata:
  name: asl-decoder
spec:
  containers:
  - name: asl-decoder
    image: pytorch/pytorch
    resources:
        limits:
          memory: 32Gi
          cpu: 4
          nvidia.com/gpu: 1
        requests:
          memory: 16Gi
          cpu: 2
          nvidia.com/gpu: 1
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts:
    - mountPath: /pvc-files/
      name: pvc-files
  volumes:
    - name: pvc-files
      persistentVolumeClaim:
        claimName: ml-pvc
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-GeForce-RTX-3090